IF NOT EXIST OUT MKDIR OUT
asm68k /k /p /o ae-,c+ SRC/MAIN.ASM, OUT/S1MP_COMBINED.BIN >OUT/S1MP_COMBINED.LOG, OUT/S1MP_COMBINED.SYM, OUT/S1MP_COMBINED.LST
romwak /b OUT/S1MP_COMBINED.BIN OUT/ep15177.ic2 OUT/ep15176.ic1